apiVersion: kafka.nais.io/v1
kind: Topic
metadata:
  name: aapen-brukernotifikasjon-beskjed-v1
  namespace: min-side
  labels:
    team: min-side
  annotations:
    dcat.data.nav.no/title: "Public input-topic for Dittnav sine beskjed-eventer"
    dcat.data.nav.no/description: "Produsenter kan sende brukernotifikasjoner til Dittnav"
    dcat.data.nav.no/keyword: "brukernotifikasjon"
spec:
  pool: nav-prod
  config:
    cleanupPolicy: delete  # delete, compact
    minimumInSyncReplicas: 1
    partitions: 4
    replication: 3  # see min/max requirements
    retentionBytes: -1  # -1 means unlimited
    retentionHours: 168  # One week
  acl:
    - team: min-side
      application: dittnav-brukernotifikasjonbestiller
      access: read   # read, write, readwrite
    - team: min-side
      application: tms-event-test-producer
      access: write
    - team: dusseldorf
      application: k9-dittnav-varsel
      access: write
    - team: team-soknad
      application: henvendelse
      access: write
    - team: teamdigisos
      application: sosialhjelp-dialog-api
      access: write
    - team: teamfamilie
      application: familie-ef-mottak
      access: write
    - team: team-esyfo
      application: esyfovarsel
      access: write
    - team: teamsykefravr
      application: isdialogmote
      access: write
    - team: pto
      application: veilarbaktivitet
      access: write
    - team: pto
      application: veilarbdialog
      access: write
    - team: teamforeldrepenger
      application: fpinfo-historikk
      access: write
    - team: bidrag
      application: farskapsportal
      access: write
