apiVersion: kafka.nais.io/v1
kind: Topic
metadata:
  name: aapen-brukernotifikasjon-oppgave-v1
  namespace: min-side
  labels:
    team: min-side
  annotations:
    dcat.data.nav.no/title: "Public input-topic for Dittnav sine oppgave-eventer"
    dcat.data.nav.no/description: "Produsenter kan sende brukernotifikasjoner til Dittnav"
    dcat.data.nav.no/keyword: "brukernotifikasjon"
spec:
  pool: nav-dev
  config:
    cleanupPolicy: delete  # delete, compact
    minimumInSyncReplicas: 1
    partitions: 4
    replication: 3  #  see min/max requirements
    retentionBytes: -1  # -1 means unlimited
    retentionHours: 168  # One week
  acl:
    - team: min-side
      application: dittnav-brukernotifikasjonbestiller
      access: read   # read, write, readwrite
    - team: personbruker
      application: dittnav-brukernotifikasjonbestiller
      access: read
    - team: min-side
      application: tms-event-test-producer
      access: write
    - team: teamdokumenthandtering
      application: dokdistdittnav
      access: write
    - team: team-soknad
      application: henvendelse
      access: write
    - team: team-soknad
      application: soknadsmottaker
      access: write
    - team: teamsykefravr
      application: isdialogmote
      access: write
    - team: flex
      application: spinnsyn-brukernotifikasjon
      access: write
    - team: flex
      application: syfosoknadbrukernotifikasjon
      access: write
    - team: pto
      application: veilarbaktivitet
      access: write
    - team: pto
      application: veilarbdialog
      access: write
    - team: teamsykmelding
      application: syfosmvarsel
      access: write
    - team: teamnks
      application: sf-brukernotifikasjon
      access: write
    - team: farskapsportal
      application: farskapsportal-api
      access: write
    - team: farskapsportal
      application: farskapsportal-api-feature
      access: write
    - team: farskapsportal
      application: asynkron
      access: write
    - team: farskapsportal
      application: asynkron-feature
      access: write
    - team: teamdigihot
      application: hm-ditt-nav
      access: write
    - team: teampam
      application: pam-brukernotifikasjon
      access: write
    - team: min-side
      application: tms-kafka-manager
      access: read
    - team: aap
      application: soknad-api
      access: write
    - team: pdl
      application: pdl-fullmakt
      access: write
    - team: bidrag
      application: bidrag-reisekostnad-api
      access: write
    - team: teamdagpenger
      application: dp-varsel
      access: write
    - team: team-esyfo
      application: esyfovarsel
      access: write
    - team: teamsykmelding
      application: sykmeldinger-backend-kafka
      access: write
