apiVersion: kafka.nais.io/v1
kind: Topic
metadata:
  name: aapen-brukernotifikasjon-done-v1
  namespace: min-side
  labels:
    team: min-side
  annotations:
    dcat.data.nav.no/title: "Public input-topic for Dittnav sine done-eventer"
    dcat.data.nav.no/description: "Produsenter kan sende brukernotifikasjoner til Dittnav"
    dcat.data.nav.no/keyword: "brukernotifikasjon"
spec:
  pool: nav-dev
  config:
    cleanupPolicy: delete  # delete, compact
    minimumInSyncReplicas: 1
    partitions: 4
    replication: 3  #  see min/max requirements
    retentionBytes: -1  # -1 means unlimited
    retentionHours: 168  # One week
  acl:
    - team: min-side
      application: dittnav-brukernotifikasjonbestiller
      access: read   # read, write, readwrite
    - team: min-side
      application: dittnav-event-aggregator
      access: write
    - team: min-side
      application: tms-event-test-producer
      access: write
    - team: teamdokumenthandtering
      application: dokdistdittnav
      access: write
    - team: min-side
      application: dittnav-event-handler
      access: write
    - team: team-soknad
      application: henvendelse
      access: write
    - team: flex
      application: spinnsyn-brukernotifikasjon
      access: write
    - team: flex
      application: syfosoknadbrukernotifikasjon
      access: write
