apiVersion: kafka.nais.io/v1
kind: Topic
metadata:
  name: aapen-brukernotifikasjon-beskjed-v1
  namespace: min-side
  labels:
    team: min-side
  annotations:
    dcat.data.nav.no/title: "Public input-topic for Dittnav sine beskjed-eventer"
    dcat.data.nav.no/description: "Produsenter kan sende brukernotifikasjoner til Dittnav"
    dcat.data.nav.no/keyword: "brukernotifikasjon"
spec:
  pool: nav-dev
  config:
    cleanupPolicy: delete  # delete, compact
    minimumInSyncReplicas: 1
    partitions: 4
    replication: 3  #  see min/max requirements
    retentionBytes: -1  # -1 means unlimited
    retentionHours: 168  # One week
  acl:
    - team: min-side
      application: dittnav-brukernotifikasjonbestiller
      access: read   # read, write, readwrite
    - team: personbruker
      application: dittnav-brukernotifikasjonbestiller
      access: read
    - team: min-side
      application: tms-event-test-producer
      access: write
    - team: teamdokumenthandtering
      application: dokdistdittnav
      access: write
    - team: dusseldorf
      application: k9-dittnav-varsel
      access: write
    - team: team-soknad
      application: henvendelse
      access: write
    - team: team-soknad
      application: soknadsmottaker
      access: write
    - team: teamdigisos
      application: sosialhjelp-dialog-api-dev
      access: write
    - team: teamfamilie
      application: familie-ef-mottak
      access: write
    - team: team-esyfo
      application: esyfovarsel
      access: write
    - team: teamsykefravr
      application: isdialogmote
      access: write
    - team: pto
      application: veilarbaktivitet
      access: write
    - team: pto
      application: veilarbdialog
      access: write
    - team: teamnks
      application: sf-brukernotifikasjon
      access: write
    - team: teamforeldrepenger
      application: fpinfo-historikk
      access: write
    - team: farskapsportal
      application: farskapsportal-api
      access: write
    - team: farskapsportal
      application: farskapsportal-api-feature
      access: write
    - team: farskapsportal
      application: asynkron
      access: write
    - team: farskapsportal
      application: asynkron-feature
      access: write
    - team: etterlatte
      application: etterlatte-notifikasjoner
      access: write
    - team: teamdigihot
      application: hm-ditt-nav
      access: write
    - team: min-side
      application: tms-kafka-manager
      access: read
    - team: helsearbeidsgiver
      application: fritakagp
      access: write
    - team: aap
      application: soknad-api
      access: write
    - team: teamdokumenthandtering
      application: varsel2
      access: write
    - team: team-researchops
      application: innbyggerpanelet-backend
      access: write
    - team: pdl
      application: pdl-fullmakt
      access: write
    - team: min-side
      application: varselinnboks
      access: write
    - team: flex
      application: flex-inntektsmelding-status
      access: write
    - team: pensjonselvbetjening
      application: pensjon-selvbetjening-soknad-alder-backend
      access: write
    - team: teamdagpenger
      application: dp-behov-brukernotifikasjon
      access: write
    - team: bidrag
      application: bidrag-reisekostnad-api
      access: write

